#!/bin/bash

USERPASS=${1:-}

set -x
set -e
mkdir -p build
task() {
	seq=$1
	sname=$2
	name=$3
	fil=$sname.md
	jq --rawfile foo $fil ". +{content:\$foo} +{sequence:$seq,shortname:\"$sname\",name:\"$name\"}" < net-task.json > build/net-task-$seq.json.out
	lwp-request -m PUT -C "$(cat ~/techopw)"  https://techo.gathering.org/api/document/task-net/$sname < build/net-task-$seq.json.out

}

task 1 task1 "Task 1: Get your distro talking to the core"
task 2 task2 "Task 2: Link up distro and edge0"
task 3 task3 "Task 3: Rinse and repeat for edge1"
task 4 task4 "Task 4: Crowd pleaser: Get the client online"
task 5 management "Management access"
